version: 2
jobs:
  build:

    docker:
      - image: amazonlinux:2017.03

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Set Docker Image Env Variable for python3.6
          command: |
            yum -y install docker
            echo 'export DOCKER_IMAGE=gobble/python:3.6' >> $BASH_ENV

      # - run:
      #     name: Building Python 3.6 Docker Image
      #     command: |
      #       docker build -t  $DOCKER_IMAGE .
      #
      #
      # - deploy:
      #     name: Pushing python 3.6 Docker Image to Docker Hub
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      #         docker push $DOCKER_IMAGE
      #       fi
